### PR TITLE
DataCite API Client

### LINKED ISSUE #102: Datacite client service
Write a service that sends requests to the Datacite endpoint.

## WDLL

* register method for creating new DOIs that have incomplete metadata or are for unpublished works
* publish method that updates or creates a DOI in a published state for a published work
* update method that updates metadata for an existing DOI
* any errors will generate exceptions with the Datacite response in the message
* successes will return the DOI string, and datacite response as a json hash

### PR DESCRIPTION
**Pull request by rschenk**
Client class to manage DOIs via DataCite. Also installs the VCR gem for
mocking of network calls.

Fixes #102

### CODE REVIEW

File: lib/data_cite/client.rb [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+          publisher: publisher
+        )
+      }
+
+      if doi.blank?
+        data[:attributes][:prefix] = prefix
+        process_response post(data: data)
+      else
+        data[:id] = doi
+        process_response put(doi: doi, data: data)
```
Comment (awead) [inline lib/data_cite/client.rb]: @rschenk we're not testing this else case.

File: lib/data_cite/client.rb [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+          errors = parsed_body.fetch('errors', [])
+          stringified_errors = errors.inspect
+          message = stringified_errors.presence || "DataCite response returned #{response.status}"
+
+          raise Error.new(message)
+        end
+
+        doi = parsed_body.dig('data', 'id')
+
+        [doi, parsed_body]
```
Comment (awead) [inline lib/data_cite/client.rb]: @rschenk According to Code Climate, we don't seem to be testing this method. 🤷‍♂
